{% set data= load_setup_py_data() %}
package:
  name: dm-ocps
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_ocps = lsst.dm.OCPS.ocps_csc:run_ocps

test:
  requires:
    - ts-conda-build =0.4
    - redis
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
  source_files:
    - python
    - bin
    - tests
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python {{ python }}
    - requests
    - setuptools
    - setuptools_scm
    - redis
    - ts-idl
    - ts-salobj
